modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/Maced/issues/"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Nova-Committee/Maced/"
credits = "Thanks for mojang's genius idea"
authors = "${mod_authors}"
[[mixins]]
config = "maced.mixins.json"
description = '''${mod_description}'''
