modLoader = "javafml"
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "https://github.com/Nova-Committee/Maced/issues/"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}
displayURL = "https://github.com/Nova-Committee/Maced/"
credits = "Thanks for mojang's genius idea"
authors = "${mod_authors}"
description = '''${mod_description}'''